export const FETCH_MORE_BEERS = 'FETCH_MORE_BEERS'
export const RESET_LIST = 'RESET_LIST'
export const FETCH_POSTS = 'FETCH_POSTS'
export const ADD_POST = 'ADD_POST'
export const SET_FILTER_NAME = 'SET_FILTER_NAME'
